In [61]:
import pandas as pd

df1 = pd.read_csv('pi_pred.csv')
df2 = pd.read_csv('fns_pred.csv')
df3 = pd.read_csv('king_pred.csv')
df4 = pd.read_csv('aira_pred.csv')

df_buy = pd.concat([df1, df2, df3, df4], ignore_index=True)
df_buy = df_buy[df_buy['action'].str.contains('BUY', na=False)].reset_index(drop=True)
df_buy

,title,pdf,analys,date,stock_name,action,price,cs,cs5,cs10,cs15,assistant
0,29/05/2025 AMATA (BUY : Fair Price : Bt 33.60)...,https://api.prod.pi.financial/cms/assets/09dc1...,Dome Kunprayoonsawad,2025-05-29,AMATA,BUY,33.60,-1.00,-2.00,-3.00,-4.00,NaN
1,26/05/2025 STECON (BUY : Fair Price : Bt 8.59)...,https://api.prod.pi.financial/cms/assets/56835...,Dome Kunprayoonsawad,2025-05-26,STECON,BUY,8.59,7.20,7.45,7.45,7.45,NaN
2,26/05/2025 SAWAD (BUY : Fair Price : Bt 23.50)...,https://api.prod.pi.financial/cms/assets/d1ecc...,Tanadech Rungsrithananon,2025-05-26,SAWAD,BUY,23.50,18.70,19.00,19.00,19.00,NaN
3,23/05/2025 SC (BUY : Fair Price : Bt 2.68) : 1...,https://api.prod.pi.financial/cms/assets/ae6dc...,Dome Kunprayoonsawad,2025-05-23,SC,BUY,2.68,1.76,1.65,1.65,1.65,NaN
4,23/05/2025 CK (BUY : Fair Price : Bt 21.20) : ...,https://api.prod.pi.financial/cms/assets/59248...,Dome Kunprayoonsawad,2025-05-23,CK,BUY,21.20,14.60,15.00,15.00,15.00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
3450,10/11/2563 CBG : 3Q63 สูงกว่าคาดจากยอดขายต่างป...,https://www.aira.co.th/upload/202011_160462889...,ศักดิ์นรินทร์ ศศานนท์,2020-11-10,CBG,BUY,94.00,116.00,119.50,125.00,125.00,NaN
3451,09/11/2563 CPN : กำไรสุทธิ 3Q/63 เพิ่มขึ้นโดดเ...,https://www.aira.co.th/upload/202210_166622307...,ศักดิ์นรินทร์ ศศานนท์,2020-11-09,CPN,BUY,72.50,44.00,52.00,55.00,55.00,NaN
3452,09/11/2563 KTB : กฤษฎีกาตีความ KTB ไม่เป็นรัฐว...,https://www.aira.co.th/upload/202210_166597011...,จิตรถดา เลขาพันธ์,2020-11-09,KTB,BUY,15.30,9.30,10.30,11.20,11.40,NaN
3453,28/10/2563 PTTGC : ราคาผลิตภัณฑ์ปิโตรเคมีเริ่ม...,https://www.aira.co.th/upload/202010_160386599...,ศักดิ์นรินทร์ ศศานนท์,2020-10-28,PTTGC,BUY,60.50,40.50,41.75,50.00,51.75,NaN
3454,21/10/2563 PTTEP: ได้รับประโยชน์จากราคาน้ำมันด...,https://www.aira.co.th/upload/202010_160326608...,ศักดิ์นรินทร์ ศศานนท์,2020-10-21,PTTEP,BUY,99.00,80.00,81.50,82.75,91.50,NaN

In [196]:
pred = []
for i in range(len(df_buy)):
    day_close = df_buy.iloc[i]['cs']
    day_close_ahead = df_buy.iloc[i]['cs15']
    if day_close_ahead > day_close  and (day_close_ahead-day_close) / day_close >= 0.03:
        pred.append(True)
    else:
        pred.append(False)
df_buy['predict'] = pred

list_analys = df_buy.analys.unique().tolist()
list_true = []
list_false = []
for i in list_analys:
    df_buy_analys = df_buy[df_buy['analys'] == i].reset_index(drop=True)
    no_true = df_buy_analys[df_buy_analys['predict'] == True].shape[0]
    no_false = df_buy_analys[df_buy_analys['predict'] == False].shape[0]
    list_true.append(no_true)
    list_false.append(no_false)
df_buy_analys = pd.DataFrame({'analys':list_analys,'true':list_true,'false':list_false})
df_buy_analys['total'] = df_buy_analys['true'] + df_buy_analys['false']
df_buy_analys['accuracy'] = df_buy_analys['true'] / df_buy_analys['total']
print(len(df_buy[df_buy['predict'] == True]),len(df_buy[df_buy['predict'] == False]))
df_buy_analys

1511 1944

                        analys  true  false  total  accuracy
0         Dome Kunprayoonsawad    40     75    115  0.347826
1     Tanadech Rungsrithananon    34     36     70  0.485714
2        Thanawich Boonchuwong    35     47     82  0.426829
3              Aomsub Ngowsiri     6      7     13  0.461538
4         Thanyatorn Songwutti    92    113    205  0.448780
5              Jitra Amornthum   225    227    452  0.497788
6         Sureeporn Teewasuwet   163    185    348  0.468391
7            Songklod Wongchai    39     29     68  0.573529
8   Nathapol Pongsukcharoenkul     8      8     16  0.500000
9             Teerapol Udomvej   144    164    308  0.467532
10       Thada Jiracharoenying     6     25     31  0.193548
11               Usanee Liurut    33     44     77  0.428571
12  Kwanwaree Apichartsataporn    10      2     12  0.833333
13       Naruedom Mujjalinkool    27     52     79  0.341772
14              Suwat Sinsadok    81    145    226  0.358407
15        Yuvanart Suwanumphai    47     83    130  0.361538
16         Veeravat Virochpoka     2      7      9  0.222222
17       Nanpicha Chungsiriwat     6      6     12  0.500000
18     Nattawat Poosunthornsri    42     77    119  0.352941
19            Nopporn Chaykaew   154    172    326  0.472393
20         Apichai Raomanachai   133    157    290  0.458621
21              Kitti Buabueng     2      5      7  0.285714
22     Piyatat Pasommanatsakul    12     20     32  0.375000
23        Meena Tunlayanitigun    33     73    106  0.311321
24      Watcharain Jongyanyong     1      2      3  0.333333
25       ศักดิ์นรินทร์ ศศานนท์    60     94    154  0.389610
26             หทัยชนก มูลวงศ์    51     58    109  0.467890
27           จิตรลดา เลขาพันธ์    15     18     33  0.454545
28           จิตรถดา เลขาพันธ์     3      5      8  0.375000
29           ประวิทย์ เจียวก๊ก     2      2      4  0.500000
30         ศรัณยู สืบสุรีย์กุล     3      3      6  0.500000
31               พลเทพ วงษ์นาค     2      3      5  0.400000

In [216]:
import pandas as pd

def trailing_stop(df_buy, stop_pct=0.05, sleep_days=5):
    exit_days = []
    for i, row in df_buy.iterrows():
        if row['action'].lower() != 'buy':
            exit_days.append(None)
            continue

        entry_price = row['cs']
        max_price = entry_price
        exit_day = 15

        for day in [5, 10, 15]:
            if day < sleep_days:
                continue
            cs_col = f'cs{day}'
            if pd.notna(row.get(cs_col)):
                price = row[cs_col]
                max_price = max(max_price, price)
                if price < max_price * (1 - stop_pct):
                    exit_day = day
                    break

        exit_days.append(exit_day)

    df_result = df_buy.copy()
    df_result['exit_trailing'] = exit_days
    return df_result

df_buy = trailing_stop(df_buy)

pred_trailing = []
for i in range(len(df_buy)):
    exit_day = df_buy.iloc[i]['exit_trailing']
    if pd.isna(exit_day):
        pred_trailing.append(False)
        continue

    entry = df_buy.iloc[i]['cs']
    cs_col = f'cs{int(exit_day)}'

    if cs_col in df_buy.columns and pd.notna(df_buy.iloc[i][cs_col]):
        future = df_buy.iloc[i][cs_col]
        gain = (future - entry) / entry
        pred_trailing.append(gain >= 0.05)
    else:
        pred_trailing.append(False)

df_buy['predict_trailing'] = pred_trailing


pred_cs15 = []
for i in range(len(df_buy)):
    entry = df_buy.iloc[i]['cs']
    if 'cs15' in df_buy.columns and pd.notna(df_buy.iloc[i]['cs15']):
        future = df_buy.iloc[i]['cs15']
        gain = (future - entry) / entry
        pred_cs15.append(gain >= 0.075)
    else:
        pred_cs15.append(False)

df_buy['predict_cs15'] = pred_cs15
df_buy['predict_combined'] = df_buy['predict_trailing'] | df_buy['predict_cs15']

list_analys = df_buy['analys'].unique().tolist()
list_true = []
list_false = []

for a in list_analys:
    df_a = df_buy[df_buy['analys'] == a].reset_index(drop=True)
    no_true = df_a[df_a['predict_combined'] == True].shape[0]
    no_false = df_a[df_a['predict_combined'] == False].shape[0]
    list_true.append(no_true)
    list_false.append(no_false)

df_buy_analys = pd.DataFrame({
    'analys': list_analys,
    'true': list_true,
    'false': list_false
})
df_buy_analys['total'] = df_buy_analys['true'] + df_buy_analys['false']
df_buy_analys['accuracy'] = df_buy_analys['true'] / df_buy_analys['total']

print("TRUE:", df_buy['predict_combined'].sum())
print("FALSE:", (~df_buy['predict_combined']).sum())

df_buy_analys

TRUE: 1312
FALSE: 2143

                        analys  true  false  total  accuracy
0         Dome Kunprayoonsawad    29     86    115  0.252174
1     Tanadech Rungsrithananon    22     48     70  0.314286
2        Thanawich Boonchuwong    24     58     82  0.292683
3              Aomsub Ngowsiri     6      7     13  0.461538
4         Thanyatorn Songwutti    67    138    205  0.326829
5              Jitra Amornthum   173    279    452  0.382743
6         Sureeporn Teewasuwet   123    225    348  0.353448
7            Songklod Wongchai    29     39     68  0.426471
8   Nathapol Pongsukcharoenkul     9      7     16  0.562500
9             Teerapol Udomvej   130    178    308  0.422078
10       Thada Jiracharoenying     6     25     31  0.193548
11               Usanee Liurut    12     65     77  0.155844
12  Kwanwaree Apichartsataporn     8      4     12  0.666667
13       Naruedom Mujjalinkool    45     34     79  0.569620
14              Suwat Sinsadok   135     91    226  0.597345
15        Yuvanart Suwanumphai    79     51    130  0.607692
16         Veeravat Virochpoka     4      5      9  0.444444
17       Nanpicha Chungsiriwat     5      7     12  0.416667
18     Nattawat Poosunthornsri    25     94    119  0.210084
19            Nopporn Chaykaew   104    222    326  0.319018
20         Apichai Raomanachai   121    169    290  0.417241
21              Kitti Buabueng     3      4      7  0.428571
22     Piyatat Pasommanatsakul    18     14     32  0.562500
23        Meena Tunlayanitigun    12     94    106  0.113208
24      Watcharain Jongyanyong     1      2      3  0.333333
25       ศักดิ์นรินทร์ ศศานนท์    59     95    154  0.383117
26             หทัยชนก มูลวงศ์    39     70    109  0.357798
27           จิตรลดา เลขาพันธ์    18     15     33  0.545455
28           จิตรถดา เลขาพันธ์     1      7      8  0.125000
29           ประวิทย์ เจียวก๊ก     1      3      4  0.250000
30         ศรัณยู สืบสุรีย์กุล     3      3      6  0.500000
31               พลเทพ วงษ์นาค     1      4      5  0.200000

In [215]:
import pandas as pd
from datetime import datetime

df_buy['date'] = pd.to_datetime(df_buy['date'], format='mixed')

def sell_signal_exit(df, sleep_days=5):
    exit_days = []

    for i, row in df.iterrows():
        if row['action'].lower() != 'buy':
            exit_days.append(None)
            continue

        stock = row['stock_name']
        entry_date = row['date']

        mask = (
            (df['stock_name'] == stock) &
            (df['action'].str.lower() == 'sell') &
            (pd.to_datetime(df['date']) >= entry_date + pd.Timedelta(days=sleep_days))
        )

        if df[mask].empty:
            exit_days.append(None)
        else:
            sell_date = df[mask]['date'].min() 
            delta_days = (sell_date - entry_date).days
            if delta_days <= 5:
                exit_day = 5
            elif delta_days <= 10:
                exit_day = 10
            else:
                exit_day = 15
            exit_days.append(exit_day)

    df_result = df.copy()
    df_result['exit_sell_signal'] = exit_days
    return df_result

df_buy = sell_signal_exit(df_buy)

pred_sell_signal = []
for i in range(len(df_buy)):
    exit_day = df_buy.iloc[i]['exit_sell_signal']
    if pd.isna(exit_day):
        pred_sell_signal.append(False)
        continue

    entry = df_buy.iloc[i]['cs']
    cs_col = f'cs{int(exit_day)}'

    if cs_col in df_buy.columns and pd.notna(df_buy.iloc[i][cs_col]):
        future = df_buy.iloc[i][cs_col]
        gain = (future - entry) / entry
        pred_sell_signal.append(gain >= 0.05)
    else:
        pred_sell_signal.append(False)

df_buy['predict_sell_signal'] = pred_sell_signal

pred_cs15 = []
for i in range(len(df_buy)):
    entry = df_buy.iloc[i]['cs']
    if 'cs15' in df_buy.columns and pd.notna(df_buy.iloc[i]['cs15']):
        future = df_buy.iloc[i]['cs15']
        gain = (future - entry) / entry
        pred_cs15.append(gain >= 0.075)
    else:
        pred_cs15.append(False)

df_buy['predict_cs15'] = pred_cs15
df_buy['predict_combined'] = df_buy['predict_sell_signal'] | df_buy['predict_cs15']

list_analys = df_buy['analys'].unique().tolist()
list_true = []
list_false = []

for a in list_analys:
    df_a = df_buy[df_buy['analys'] == a].reset_index(drop=True)
    no_true = df_a[df_a['predict_combined'] == True].shape[0]
    no_false = df_a[df_a['predict_combined'] == False].shape[0]
    list_true.append(no_true)
    list_false.append(no_false)

df_buy_analys = pd.DataFrame({
    'analys': list_analys,
    'true': list_true,
    'false': list_false
})
df_buy_analys['total'] = df_buy_analys['true'] + df_buy_analys['false']
df_buy_analys['accuracy'] = df_buy_analys['true'] / df_buy_analys['total']

print("TRUE:", df_buy['predict_combined'].sum())
print("FALSE:", (~df_buy['predict_combined']).sum())

df_buy_analys

TRUE: 955
FALSE: 2500

                        analys  true  false  total  accuracy
0         Dome Kunprayoonsawad    19     96    115  0.165217
1     Tanadech Rungsrithananon    16     54     70  0.228571
2        Thanawich Boonchuwong    13     69     82  0.158537
3              Aomsub Ngowsiri     3     10     13  0.230769
4         Thanyatorn Songwutti    37    168    205  0.180488
5              Jitra Amornthum   119    333    452  0.263274
6         Sureeporn Teewasuwet    83    265    348  0.238506
7            Songklod Wongchai    24     44     68  0.352941
8   Nathapol Pongsukcharoenkul     7      9     16  0.437500
9             Teerapol Udomvej    93    215    308  0.301948
10       Thada Jiracharoenying     0     31     31  0.000000
11               Usanee Liurut     6     71     77  0.077922
12  Kwanwaree Apichartsataporn     8      4     12  0.666667
13       Naruedom Mujjalinkool    39     40     79  0.493671
14              Suwat Sinsadok   117    109    226  0.517699
15        Yuvanart Suwanumphai    63     67    130  0.484615
16         Veeravat Virochpoka     3      6      9  0.333333
17       Nanpicha Chungsiriwat     5      7     12  0.416667
18     Nattawat Poosunthornsri    15    104    119  0.126050
19            Nopporn Chaykaew    71    255    326  0.217791
20         Apichai Raomanachai    96    194    290  0.331034
21              Kitti Buabueng     3      4      7  0.428571
22     Piyatat Pasommanatsakul    17     15     32  0.531250
23        Meena Tunlayanitigun    10     96    106  0.094340
24      Watcharain Jongyanyong     1      2      3  0.333333
25       ศักดิ์นรินทร์ ศศานนท์    46    108    154  0.298701
26             หทัยชนก มูลวงศ์    20     89    109  0.183486
27           จิตรลดา เลขาพันธ์    17     16     33  0.515152
28           จิตรถดา เลขาพันธ์     1      7      8  0.125000
29           ประวิทย์ เจียวก๊ก     1      3      4  0.250000
30         ศรัณยู สืบสุรีย์กุล     1      5      6  0.166667
31               พลเทพ วงษ์นาค     1      4      5  0.200000

In [ ]:
import pandas as pd
from datetime import timedelta

def combined_exit_strategy(df, stop_pct=0.05, sleep_days=5):
    ts_flags = []
    ss_flags = []
    cs15_flags = []

    for i, row in df.iterrows():
        if row['action'].lower() != 'buy':
            ts_flags.append(False)
            ss_flags.append(False)
            cs15_flags.append(False)
            continue

        entry_price = row['cs']
        entry_date = pd.to_datetime(row['date'])

        # Trailing Stop Exit (after sleep_days)
        max_price = entry_price
        ts_triggered = False
        for day in [5, 10, 15]:
            if day < sleep_days:
                continue
            col = f'cs{day}'
            if pd.notna(row.get(col)):
                price = row[col]
                max_price = max(max_price, price)
                if price < max_price * (1 - stop_pct):
                    ts_triggered = True
                    break
        ts_flags.append(ts_triggered)

        # Sell Signal with gain ≥ 5%
        ss_triggered = False
        df_sell = df[
            (df['stock_name'] == row['stock_name']) &
            (df['action'].str.lower() == 'sell') &
            (pd.to_datetime(df['date']) >= entry_date + timedelta(days=sleep_days))
        ]
        if not df_sell.empty:
            first_sell_date = pd.to_datetime(df_sell['date'].min())
            if 'cs' in df_sell.columns:
                price_sell = df_sell[df_sell['date'] == first_sell_date]['cs'].values[0]
                gain = (price_sell - entry_price) / entry_price
                if gain >= 0.05:
                    ss_triggered = True
        ss_flags.append(ss_triggered)

        # cs15 gain ≥ 7.5%
        if pd.notna(row.get('cs15')):
            gain15 = (row['cs15'] - entry_price) / entry_price
            cs15_flags.append(gain15 >= 0.03)
        else:
            cs15_flags.append(False)

    df_result = df.copy()
    df_result['ts_flag'] = ts_flags
    df_result['ss_flag'] = ss_flags
    df_result['cs15_flag'] = cs15_flags

    # Final prediction:
    # ต้องมี ts_flag หรือ ss_flag ก่อน (อย่างน้อยหนึ่ง True)
    # และ cs15_flag ต้องเป็น True ด้วย
    df_result['predict_combined'] = ((df_result['ts_flag'] | df_result['ss_flag']) | df_result['cs15_flag'])

    return df_result

# Run strategy
df_buy = combined_exit_strategy(df_buy)

# Accuracy summary (เหมือนเดิม)
list_analys = df_buy['analys'].unique().tolist()
list_true = []
list_false = []

for a in list_analys:
    df_a = df_buy[df_buy['analys'] == a].reset_index(drop=True)
    no_true = df_a[df_a['predict_combined'] == True].shape[0]
    no_false = df_a[df_a['predict_combined'] == False].shape[0]
    list_true.append(no_true)
    list_false.append(no_false)

df_buy_analys = pd.DataFrame({
    'analys': list_analys,
    'true': list_true,
    'false': list_false
})
df_buy_analys['total'] = df_buy_analys['true'] + df_buy_analys['false']
df_buy_analys['accuracy'] = df_buy_analys['true'] / df_buy_analys['total']

# Output summary
print("TRUE:", df_buy['predict_combined'].sum())
print("FALSE:", (~df_buy['predict_combined']).sum())

df_buy_analys

TRUE: 1646
FALSE: 1809

                        analys  true  false  total  accuracy
0         Dome Kunprayoonsawad    45     70    115  0.391304
1     Tanadech Rungsrithananon    35     35     70  0.500000
2        Thanawich Boonchuwong    36     46     82  0.439024
3              Aomsub Ngowsiri     6      7     13  0.461538
4         Thanyatorn Songwutti    99    106    205  0.482927
5              Jitra Amornthum   243    209    452  0.537611
6         Sureeporn Teewasuwet   160    188    348  0.459770
7            Songklod Wongchai    40     28     68  0.588235
8   Nathapol Pongsukcharoenkul     9      7     16  0.562500
9             Teerapol Udomvej   176    132    308  0.571429
10       Thada Jiracharoenying     6     25     31  0.193548
11               Usanee Liurut    34     43     77  0.441558
12  Kwanwaree Apichartsataporn    10      2     12  0.833333
13       Naruedom Mujjalinkool    51     28     79  0.645570
14              Suwat Sinsadok   165     61    226  0.730088
15        Yuvanart Suwanumphai    93     37    130  0.715385
16         Veeravat Virochpoka     5      4      9  0.555556
17       Nanpicha Chungsiriwat     5      7     12  0.416667
18     Nattawat Poosunthornsri    27     92    119  0.226891
19            Nopporn Chaykaew    97    229    326  0.297546
20         Apichai Raomanachai   113    177    290  0.389655
21              Kitti Buabueng     3      4      7  0.428571
22     Piyatat Pasommanatsakul     7     25     32  0.218750
23        Meena Tunlayanitigun    22     84    106  0.207547
24      Watcharain Jongyanyong     2      1      3  0.666667
25       ศักดิ์นรินทร์ ศศานนท์    70     84    154  0.454545
26             หทัยชนก มูลวงศ์    55     54    109  0.504587
27           จิตรลดา เลขาพันธ์    22     11     33  0.666667
28           จิตรถดา เลขาพันธ์     3      5      8  0.375000
29           ประวิทย์ เจียวก๊ก     2      2      4  0.500000
30         ศรัณยู สืบสุรีย์กุล     3      3      6  0.500000
31               พลเทพ วงษ์นาค     2      3      5  0.400000

In [188]:
(df_buy['exit_trailing'] == df_buy['exit_sell_signal']).value_counts()

False    3455
Name: count, dtype: int64

In [190]:
(df_buy['predict_trailing'] == df_buy['predict_sell_signal']).value_counts()

True     2237
False    1218
Name: count, dtype: int64

In [146]:
list_analys = df_buy.analys.unique().tolist()
list_stock = df_buy.stock_name.unique().tolist()
# Initialize an empty DataFrame with rows as list_stock and columns as list_analys
accuracy_matrix = pd.DataFrame(index=list_stock, columns=list_analys)

# Loop through each stock and analyst to calculate accuracy
for stock in list_stock:
    for analys in list_analys:
        # Filter the DataFrame for the specific stock and analyst
        df_filtered = df_buy[(df_buy['stock_name'] == stock) & (df_buy['analys'] == analys)]
        
        # Calculate accuracy if there are rows for this combination
        if not df_filtered.empty:
            no_true = df_filtered[df_filtered['predict_combined'] == True].shape[0]
            total = df_filtered.shape[0]
            accuracy = no_true / total
        else:
            accuracy = None  # No data for this combination
        
        # Assign the accuracy to the corresponding cell
        accuracy_matrix.loc[stock, analys] = accuracy

# Display the accuracy matrix
accuracy_matrix

,Dome Kunprayoonsawad,Tanadech Rungsrithananon,Thanawich Boonchuwong,Aomsub Ngowsiri,Thanyatorn Songwutti,Jitra Amornthum,Sureeporn Teewasuwet,Songklod Wongchai,Nathapol Pongsukcharoenkul,Teerapol Udomvej,...,Piyatat Pasommanatsakul,Meena Tunlayanitigun,Watcharain Jongyanyong,ศักดิ์นรินทร์ ศศานนท์,หทัยชนก มูลวงศ์,จิตรลดา เลขาพันธ์,จิตรถดา เลขาพันธ์,ประวิทย์ เจียวก๊ก,ศรัณยู สืบสุรีย์กุล,พลเทพ วงษ์นาค
AMATA,0.125,None,None,None,None,0.25,None,None,None,None,...,0.2,None,None,None,None,None,None,None,None,None
STECON,0.4,None,None,None,0.333333,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
SAWAD,None,0.0,None,None,None,None,None,None,None,None,...,None,0.0,None,None,None,None,None,None,None,None
SC,0.25,None,None,None,0.366667,None,None,None,None,None,...,None,None,None,0.0,0.0,1.0,None,None,None,None
CK,0.0,None,None,None,0.428571,None,None,None,None,None,...,0.8,None,0.0,0.25,None,None,None,None,1.0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZIGA,None,None,None,None,None,None,None,None,None,None,...,None,None,None,0.5,None,None,None,None,None,None
SAMART,None,None,None,None,None,None,None,None,None,None,...,None,None,None,1.0,None,None,None,None,None,None
BIZ,None,None,None,None,None,None,None,None,None,None,...,None,None,None,1.0,None,None,None,None,None,None
CPT,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,1.0
SWINE,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,1.0,None,None,None,None

In [147]:
rows = []

for stock in list_stock:
    df_filtered = df_buy[df_buy['stock_name'] == stock]
    
    stock_analysts = df_filtered['analys'].unique().tolist()
    
    row = [stock, len(stock_analysts)]
    
    for i, analys in enumerate(stock_analysts, start=1):
        df_analyst = df_filtered[df_filtered['analys'] == analys]
        
        num_predictions = df_analyst.shape[0]
        accuracy = df_analyst[df_analyst['predict_combined'] == True].shape[0] / num_predictions
        
        row.extend([analys, num_predictions, accuracy])
    
    rows.append(row)

columns = ['stock_name', 'number_of_analysts']
for i in range(1, max(len(row) - 2 for row in rows) // 3 + 1):
    columns.extend([f'analys#{i}_name', f'analys#{i}_num_predictions', f'analys#{i}_accuracy'])

detailed_df = pd.DataFrame(rows, columns=columns)

detailed_df

,stock_name,number_of_analysts,analys#1_name,analys#1_num_predictions,analys#1_accuracy,analys#2_name,analys#2_num_predictions,analys#2_accuracy,analys#3_name,analys#3_num_predictions,...,analys#7_accuracy,analys#8_name,analys#8_num_predictions,analys#8_accuracy,analys#9_name,analys#9_num_predictions,analys#9_accuracy,analys#10_name,analys#10_num_predictions,analys#10_accuracy
0,AMATA,5,Dome Kunprayoonsawad,8,0.125,Jitra Amornthum,4.0,0.250000,Apichai Raomanachai,19.0,...,NaN,None,NaN,NaN,None,NaN,NaN,None,NaN,NaN
1,STECON,3,Dome Kunprayoonsawad,5,0.400,Thanyatorn Songwutti,3.0,0.333333,Apichai Raomanachai,3.0,...,NaN,None,NaN,NaN,None,NaN,NaN,None,NaN,NaN
2,SAWAD,4,Tanadech Rungsrithananon,1,0.000,Usanee Liurut,3.0,0.000000,Yuvanart Suwanumphai,6.0,...,NaN,None,NaN,NaN,None,NaN,NaN,None,NaN,NaN
3,SC,5,Dome Kunprayoonsawad,4,0.250,Thanyatorn Songwutti,30.0,0.366667,ศักดิ์นรินทร์ ศศานนท์,2.0,...,NaN,None,NaN,NaN,None,NaN,NaN,None,NaN,NaN
4,CK,8,Dome Kunprayoonsawad,6,0.000,Thanyatorn Songwutti,21.0,0.428571,Apichai Raomanachai,22.0,...,0.25,ศรัณยู สืบสุรีย์กุล,1.0,1.0,None,NaN,NaN,None,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338,ZIGA,1,ศักดิ์นรินทร์ ศศานนท์,2,0.500,None,NaN,NaN,None,NaN,...,NaN,None,NaN,NaN,None,NaN,NaN,None,NaN,NaN
339,SAMART,1,ศักดิ์นรินทร์ ศศานนท์,1,1.000,None,NaN,NaN,None,NaN,...,NaN,None,NaN,NaN,None,NaN,NaN,None,NaN,NaN
340,BIZ,1,ศักดิ์นรินทร์ ศศานนท์,2,1.000,None,NaN,NaN,None,NaN,...,NaN,None,NaN,NaN,None,NaN,NaN,None,NaN,NaN
341,CPT,1,พลเทพ วงษ์นาค,1,1.000,None,NaN,NaN,None,NaN,...,NaN,None,NaN,NaN,None,NaN,NaN,None,NaN,NaN
342,SWINE,1,จิตรลดา เลขาพันธ์,1,1.000,None,NaN,NaN,None,NaN,...,NaN,None,NaN,NaN,None,NaN,NaN,None,NaN,NaN

In [253]:
# 1. Accuracy ต่อหุ้น แต่ละ Analyst
def accuracy_per_stock_analyst(df, min_preds=3):
    rows = []

    for stock in df['stock_name'].unique():
        df_stock = df[df['stock_name'] == stock]
        for analyst in df_stock['analys'].unique():
            df_analyst = df_stock[df_stock['analys'] == analyst]
            num_preds = df_analyst.shape[0]
            num_correct = df_analyst[df_analyst['predict_combined'] == True].shape[0]
            accuracy = num_correct / num_preds if num_preds > 0 else None

            rows.append([
                stock,
                analyst,
                num_preds,
                num_correct,
                round(accuracy, 4) if accuracy is not None else None
            ])

    accuracy_by_stock_analyst = pd.DataFrame(
        rows,
        columns=['stock_name', 'analyst', 'num_predictions', 'num_correct', 'accuracy']
    )

    filtered_df = accuracy_by_stock_analyst[accuracy_by_stock_analyst['num_predictions'] >= min_preds]
    filtered_df = filtered_df.sort_values(by='accuracy', ascending=False).reset_index(drop=True)

    print(f"มีทั้งหมด {len(filtered_df)} ที่ pred >= {min_preds} ครั้ง")
    return filtered_df

df_result = accuracy_per_stock_analyst(df_buy, min_preds=3)
display(df_result)

มีทั้งหมด 363 ที่ pred >= 3 ครั้ง

,stock_name,analyst,num_predictions,num_correct,accuracy
0,"AAV,",Teerapol Udomvej,3,3,1.0
1,"BPP,",Suwat Sinsadok,3,3,1.0
2,"KBANK,",Yuvanart Suwanumphai,4,4,1.0
3,"MTC,",Yuvanart Suwanumphai,3,3,1.0
4,"BCPG,",Suwat Sinsadok,3,3,1.0
...,...,...,...,...,...
358,TRUE,Piyatat Pasommanatsakul,4,0,0.0
359,GLOCON,Sureeporn Teewasuwet,4,0,0.0
360,NER,Dome Kunprayoonsawad,4,0,0.0
361,NRF,Sureeporn Teewasuwet,3,0,0.0
362,UNIQ,Piyatat Pasommanatsakul,4,0,0.0

In [252]:
display(df_result[df_result['stock_name'] == 'PTT'])

    stock_name                analyst  num_predictions  num_correct  accuracy
252        PTT        หทัยชนก มูลวงศ์                3            1    0.3333
253        PTT         Suwat Sinsadok                3            1    0.3333
281        PTT       Nopporn Chaykaew               24            8    0.3333
327        PTT  ศักดิ์นรินทร์ ศศานนท์                6            1    0.1667

In [248]:
def compute_overall_analyst_accuracy():
    rows = []
    for stock in df_buy['stock_name'].unique():
        df_stock = df_buy[df_buy['stock_name'] == stock]
        for analyst in df_stock['analys'].unique():
            df_analyst = df_stock[df_stock['analys'] == analyst]
            num_preds = df_analyst.shape[0]
            num_correct = df_analyst[df_analyst['predict_combined'] == True].shape[0]
            rows.append([
                stock,
                analyst,
                num_preds,
                num_correct
            ])

    df_all = pd.DataFrame(
        rows,
        columns=['stock_name', 'analyst', 'num_predictions', 'num_correct']
    )
    df_agg = df_all.groupby('analyst').agg({
        'num_predictions': 'sum',
        'num_correct': 'sum'
    }).reset_index()

    df_agg['accuracy'] = (df_agg['num_correct'] / df_agg['num_predictions']).round(4)
    df_agg = df_agg.sort_values(by='accuracy', ascending=False).reset_index(drop=True)
    return df_agg

# เรียกฟังก์ชันเก็บผลลัพธ์ไว้ตัวแปร
df_analyst_accuracy = compute_overall_analyst_accuracy()

def get_analyst_accuracy(analyst_name=None):
    if analyst_name is None:
        # ถ้าไม่ใส่ชื่อ analyst, แสดงทั้งหมด
        return df_analyst_accuracy
    else:
        # ถ้าใส่ชื่อ analyst, กรองแค่ชื่อที่ตรงกัน (case-insensitive)
        return df_analyst_accuracy[df_analyst_accuracy['analyst'].str.lower() == analyst_name.lower()]

# ตัวอย่างเรียกดูทั้งหมด
display(get_analyst_accuracy())

                       analyst  num_predictions  num_correct  accuracy
0   Kwanwaree Apichartsataporn               12           10    0.8333
1               Suwat Sinsadok              226          165    0.7301
2         Yuvanart Suwanumphai              130           93    0.7154
3       Watcharain Jongyanyong                3            2    0.6667
4            จิตรลดา เลขาพันธ์               33           22    0.6667
5        Naruedom Mujjalinkool               79           51    0.6456
6            Songklod Wongchai               68           40    0.5882
7             Teerapol Udomvej              308          176    0.5714
8   Nathapol Pongsukcharoenkul               16            9    0.5625
9          Veeravat Virochpoka                9            5    0.5556
10             Jitra Amornthum              452          243    0.5376
11             หทัยชนก มูลวงศ์              109           55    0.5046
12    Tanadech Rungsrithananon               70           35    0.5000
13           ประวิทย์ เจียวก๊ก                4            2    0.5000
14         ศรัณยู สืบสุรีย์กุล                6            3    0.5000
15        Thanyatorn Songwutti              205           99    0.4829
16             Aomsub Ngowsiri               13            6    0.4615
17        Sureeporn Teewasuwet              348          160    0.4598
18       ศักดิ์นรินทร์ ศศานนท์              154           70    0.4545
19               Usanee Liurut               77           34    0.4416
20       Thanawich Boonchuwong               82           36    0.4390
21              Kitti Buabueng                7            3    0.4286
22       Nanpicha Chungsiriwat               12            5    0.4167
23               พลเทพ วงษ์นาค                5            2    0.4000
24        Dome Kunprayoonsawad              115           45    0.3913
25         Apichai Raomanachai              290          113    0.3897
26           จิตรถดา เลขาพันธ์                8            3    0.3750
27            Nopporn Chaykaew              326           97    0.2975
28     Nattawat Poosunthornsri              119           27    0.2269
29     Piyatat Pasommanatsakul               32            7    0.2188
30        Meena Tunlayanitigun              106           22    0.2075
31       Thada Jiracharoenying               31            6    0.1935

In [249]:
display(get_analyst_accuracy('Thada Jiracharoenying'))

                  analyst  num_predictions  num_correct  accuracy
31  Thada Jiracharoenying               31            6    0.1935

In [ ]:
future_close_cols = ['cs5','cs10','cs15']

def calculate_holding_days(row):
    day_close = row['cs']
    for day, col in enumerate(future_close_cols, start=1):
        future_price = row[col]
        if pd.isna(future_price):
            continue
        # ถ้ากำไรเกิน 3%
        if (future_price - day_close) / day_close >= 0.03:
            return day  
    return None  

df_buy['holding_days'] = df_buy.apply(calculate_holding_days, axis=1)

rows = []
for stock in df_buy['stock_name'].unique():
    df_stock = df_buy[df_buy['stock_name'] == stock]
    for analyst in df_stock['analys'].unique():
        df_analyst = df_stock[df_stock['analys'] == analyst]
        count_trades = df_analyst.shape[0]
        avg_holding = df_analyst['holding_days'].dropna().mean() if not df_analyst['holding_days'].dropna().empty else None
        rows.append([stock, analyst, count_trades, round(avg_holding, 2) if avg_holding is not None else None])

df_avg_holding = pd.DataFrame(rows, columns=['stock_name', 'analyst', 'num_trades', 'avg_holding_days'])

def get_avg_holding_days(stock_name=None, analyst=None):
    df_filtered = df_avg_holding
    if stock_name is not None:
        df_filtered = df_filtered[df_filtered['stock_name'] == stock_name]
    if analyst is not None:
        df_filtered = df_filtered[df_filtered['analyst'] == analyst]
    if df_filtered.empty:
        print("ไม่พบข้อมูลที่ตรงกับเงื่อนไข")
        return None
    return df_filtered

print("เฉลี่ยถือหุ้นของ Dome Kunprayoonsawad:")
display(get_avg_holding_days(analyst='Dome Kunprayoonsawad'))

print("เฉลี่ยถือหุ้นของหุ้น AMATA:")
display(get_avg_holding_days(stock_name='AMATA'))

print("เฉลี่ยถือหุ้นของ Dome Kunprayoonsawad กับหุ้น AMATA:")
display(get_avg_holding_days(stock_name='AMATA', analyst='Dome Kunprayoonsawad'))

เฉลี่ยถือหุ้นของ Dome Kunprayoonsawad:

    stock_name               analyst  num_trades  avg_holding_days
0        AMATA  Dome Kunprayoonsawad           8              1.00
5       STECON  Dome Kunprayoonsawad           5              1.00
12          SC  Dome Kunprayoonsawad           4              2.00
17          CK  Dome Kunprayoonsawad           6               NaN
34         NER  Dome Kunprayoonsawad           4               NaN
35         SAT  Dome Kunprayoonsawad           8              2.00
39         TVO  Dome Kunprayoonsawad           4              1.00
41         AAV  Dome Kunprayoonsawad           6              2.00
45         CPF  Dome Kunprayoonsawad           7              1.00
51         AOT  Dome Kunprayoonsawad           4              2.00
80         WHA  Dome Kunprayoonsawad           7              1.33
101       GFPT  Dome Kunprayoonsawad           7              1.50
103        SAV  Dome Kunprayoonsawad           3              1.00
115       TACC  Dome Kunprayoonsawad           3              2.00
118        TFM  Dome Kunprayoonsawad           4              1.50
120         TU  Dome Kunprayoonsawad           7              1.50
137        CPN  Dome Kunprayoonsawad           9              1.40
142        ITC  Dome Kunprayoonsawad           8              1.00
189         XO  Dome Kunprayoonsawad           4              2.00
192         BA  Dome Kunprayoonsawad           3              1.00
215        KSL  Dome Kunprayoonsawad           2              1.00
238         AH  Dome Kunprayoonsawad           1              2.00
243       STEC  Dome Kunprayoonsawad           1              1.00

เฉลี่ยถือหุ้นของหุ้น AMATA:

  stock_name                  analyst  num_trades  avg_holding_days
0      AMATA     Dome Kunprayoonsawad           8              1.00
1      AMATA          Jitra Amornthum           4              1.00
2      AMATA      Apichai Raomanachai          19              1.54
3      AMATA           Kitti Buabueng           1              3.00
4      AMATA  Piyatat Pasommanatsakul           5              1.00

เฉลี่ยถือหุ้นของ Dome Kunprayoonsawad กับหุ้น AMATA:

  stock_name               analyst  num_trades  avg_holding_days
0      AMATA  Dome Kunprayoonsawad           8               1.0

In [276]:
display(df_avg_holding)

    stock_name                  analyst  num_trades  avg_holding_days
0        AMATA     Dome Kunprayoonsawad           8              1.00
1        AMATA          Jitra Amornthum           4              1.00
2        AMATA      Apichai Raomanachai          19              1.54
3        AMATA           Kitti Buabueng           1              3.00
4        AMATA  Piyatat Pasommanatsakul           5              1.00
..         ...                      ...         ...               ...
667       ZIGA    ศักดิ์นรินทร์ ศศานนท์           2              1.00
668     SAMART    ศักดิ์นรินทร์ ศศานนท์           1              2.00
669        BIZ    ศักดิ์นรินทร์ ศศานนท์           2              1.50
670        CPT            พลเทพ วงษ์นาค           1              1.00
671      SWINE        จิตรลดา เลขาพันธ์           1              1.00

[672 rows x 4 columns]

In [ ]:
import json

def get_analysts_for_stock(specific_stock, detailed_df = detailed_df):
    # specific_stock = "HMPRO"  

    df_filtered = detailed_df[detailed_df['stock_name'] == specific_stock]

    if df_filtered.empty:
        output = {
            "error": f"Stock name '{specific_stock}' not found in the dataset."
        }
    else:
        analyst_details = []
        for i in range(1, int(df_filtered['number_of_analysts'].values[0]) + 1):
            analyst_name = df_filtered[f'analys#{i}_name'].values[0]
            num_predictions = int(df_filtered[f'analys#{i}_num_predictions'].values[0])  
            accuracy = float(df_filtered[f'analys#{i}_accuracy'].values[0]) 
            analyst_details.append({
                "analyst_name": analyst_name,
                "num_predictions": num_predictions,
                "accuracy": accuracy
            })

        analysts = sorted(analyst_details, key=lambda x: (x['accuracy'], x['num_predictions']), reverse=True)

        output = {
            "stock_name": specific_stock,
            "num_analysts": int(df_filtered['number_of_analysts'].values[0]), 
            "analysts": analysts
        }

    # with open(f"{specific_stock}_top_5_analysts.json", "w", encoding="utf-8") as json_file:
    #     json.dump(output, json_file, ensure_ascii=False, indent=4)

    print(json.dumps(output, ensure_ascii=False, indent=4)) 
    return output

In [272]:
get_analysts_for_stock("KBANK")

{
    "stock_name": "KBANK",
    "analysts": [
        {
            "analyst_name": "ศักดิ์นรินทร์ ศศานนท์",
            "num_predictions": 4,
            "accuracy": 0.75
        },
        {
            "analyst_name": "Meena Tunlayanitigun",
            "num_predictions": 12,
            "accuracy": 0.3333333333333333
        },
        {
            "analyst_name": "Apichai Raomanachai",
            "num_predictions": 6,
            "accuracy": 0.3333333333333333
        },
        {
            "analyst_name": "Yuvanart Suwanumphai",
            "num_predictions": 8,
            "accuracy": 0.25
        },
        {
            "analyst_name": "Tanadech Rungsrithananon",
            "num_predictions": 6,
            "accuracy": 0.16666666666666666
        }
    ]
}

{'stock_name': 'KBANK',
 'analysts': [{'analyst_name': 'ศักดิ์นรินทร์ ศศานนท์',
   'num_predictions': 4,
   'accuracy': 0.75},
  {'analyst_name': 'Meena Tunlayanitigun',
   'num_predictions': 12,
   'accuracy': 0.3333333333333333},
  {'analyst_name': 'Apichai Raomanachai',
   'num_predictions': 6,
   'accuracy': 0.3333333333333333},
  {'analyst_name': 'Yuvanart Suwanumphai',
   'num_predictions': 8,
   'accuracy': 0.25},
  {'analyst_name': 'Tanadech Rungsrithananon',
   'num_predictions': 6,
   'accuracy': 0.16666666666666666}]}

In [160]:
import requests
stock = "KBANK"
url = f'http://127.0.0.1:5000/' + stock
data = requests.get(url).json()
print(data)

{'analysts': [{'accuracy': 0.75, 'analyst_name': 'ศักดิ์นรินทร์ ศศานนท์', 'num_predictions': 4}, {'accuracy': 0.36363636363636365, 'analyst_name': 'Apichai Raomanachai', 'num_predictions': 11}, {'accuracy': 0.3333333333333333, 'analyst_name': 'Meena Tunlayanitigun', 'num_predictions': 12}, {'accuracy': 0.25, 'analyst_name': 'Yuvanart Suwanumphai', 'num_predictions': 8}, {'accuracy': 0.16666666666666666, 'analyst_name': 'Tanadech Rungsrithananon', 'num_predictions': 6}], 'stock_name': 'KBANK'}